[theme]
base = "light"
primaryColor = "#6655E8"
backgroundColor = "#F4F3FF"
secondaryBackgroundColor = "#F0EFFB"
textColor = "#24234A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[browser]
gatherUsageStats = false
